version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "4321:4321"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/letsencrypt/live
      - ./html:/usr/share/nginx/html
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./webroot:/var/www/html
    entrypoint: 
      - /bin/sh
      - -c
      - ./certbot_renew.sh